version: '2'
services:
  jenkins:
    build:
        context: ./jenkins
        args:
           - DOCKER_GROUP_ID=992
    ports:
        - 8080:8080
    volumes:
        - /var/jenkins:/var/jenkins_home
        - ../server:/src
        - /var/run/docker.sock:/var/run/docker.sock
    environment:
        - LOCAL_GROUP_ID=992
    privileged: true